name: Bug 报告
description: 提交一个 Bug
labels:
  - "bug"

body:
  - type: markdown
    attributes:
      value: |
        感谢你来到这里

        在反馈前, 请确认你已经做了下面这些事情
        - 阅读过 [「提问的智慧」](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
        - 阅读过 [「如何有效地报告 Bug」](https://www.chiark.greenend.org.uk/~sgtatham/bugs-cn.html)
        - 对照过 [Releases](https://github.com/cssxsh/fix-protocol-version/releases)，相关问题未在近期更新中解决
        - 搜索了已有的 [issues](https://github.com/cssxsh/fix-protocol-version/issues?q=is%3Aissue) 列表中有没相关的信息
        - 阅读了 [README](https://github.com/cssxsh/fix-protocol-version#readme)


  - type: textarea
    id: issue-description
    attributes:
      label: 问题描述
      description: 在此详细描述你遇到的问题
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 复现
      description: 在这里简略说明如何让这个问题再次发生
      placeholder: |
        在这里简略说明如何让这个问题再次发生
        可使用 1.  2.  3.  的列表格式，或其他任意恰当的格式
        如果你不确定如何复现, 请尽量描述发生当时的情景
    validations:
      required: true

  - type: input
    id: version-mirai-core
    attributes:
      label: mirai-core 版本
      description: "填写你正在使用的版本号，如 `2.15.0`"
      placeholder: 2.15.0
    validations:
      required: true

  - type: dropdown
    id: bot-protocol
    attributes:
      label: bot-protocol
      options:
        - ANDROID_PHONE
        - ANDROID_PAD
        - ANDROID_WATCH
        - IPAD
        - MACOS
    validations:
      required: true

  - type: textarea
    id: encrypt-service
    attributes:
      label: 签名服务
      description: |
        如果你正在使用 unidbg-fetch-qsign, 请提供版本号
      placeholder: |
        magic-signer-guide
    validations:
      required: true

  - type: textarea
    id: journal-system
    attributes:
      label: 系统日志
      description: |
        请提供全面的相关日志. 请不要截图.
        如果日志过大, 可以在 `补充信息` 上传文件.
      render: "plain text"
    validations:
      required: true

  - type: textarea
    id: journal-network
    attributes:
      label: 网络日志
      description: |
        如果网络日志 (Net xxx) 不包含在系统日志中, 请额外提供网络日志. 若已经包含, 请忽略.
        请提供全面的网络日志. 请不要截图.
        若使用 Mirai Console 一般网络日志位于 bots/<****>/logs 里
        如果日志过大, 可以在 `补充信息` 上传文件.
      render: "plain text"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 补充信息
      description: 如有必要，你可以在下文继续添加其他信息

  - type: markdown
    attributes:
      value: |
        ----

        在发出 issue 前, 请确认

        - 全部信息已经填写完毕, 特别是 「其他组件版本」
        - 报告中没有令人反感的语言
        - 「复现」的描述是否足够详细准确

